spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://192.18.135.132:3306/user_center'
    username: pangmin
    password: 574817621
    # Session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0